import type { APIRoute } from "astro";

export const GET: APIRoute = () => {
  return Response.json([
    {
      name: "Expert",
      poetics: 0,
      uncapped: 60,
      capped: 40,
      gil: 7200,
      seals: 0,
      bonus: null,
    },
    {
      name: "Level Cap Dungeons",
      poetics: 0,
      uncapped: 100,
      capped: 15,
      gil: 7200,
      seals: 0,
      bonus: null,
    },
    {
      name: "High-level Dungeons",
      poetics: 100,
      uncapped: 120,
      capped: 0,
      gil: 7050,
      seals: 0,
      bonus: null,
    },
    {
      name: "Leveling",
      poetics: 0,
      uncapped: 100,
      capped: 20,
      gil: 7770,
      seals: 0,
      bonus: null,
    },
    {
      name: "Trials",
      poetics: 0,
      uncapped: 60,
      capped: 15,
      gil: 12000,
      seals: 0,
      bonus: null,
    },
    {
      name: "Main Scenario",
      poetics: 350,
      uncapped: 100,
      capped: 50,
      gil: 9000,
      seals: 0,
      bonus: null,
    },
    {
      name: "Alliance Raids",
      poetics: 120,
      uncapped: 120,
      capped: 50,
      gil: 12000,
      seals: 0,
      bonus: null,
    },
    {
      name: "Normal Raids",
      poetics: 80,
      uncapped: 60,
      capped: 20,
      gil: 12000,
      seals: 0,
      bonus: null,
    },
    {
      name: "Mentor",
      poetics: 0,
      uncapped: 30,
      capped: 10,
      gil: 7050,
      seals: 0,
      bonus: null,
    },
    {
      name: "Frontline",
      poetics: 80,
      uncapped: 50,
      capped: 20,
      gil: 0,
      seals: 0,
      bonus: null,
    },
  ]);
};
